# Generated by Django 6.0.6 on 2026-07-06 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rejissyor', models.CharField(max_length=255)),
                ('chiqarilgan_yil', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2026)])),
                ('janr', models.CharField(max_length=100)),
                ('reyting', models.FloatField(default=0)),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
